config/routes.rb
Zwaj::Application.routes.draw do
  
  resources :notifications

  resources :events

  resources :services

  resources :activities

  resources :themes

  resources :albums

  resources :gifts

  resources :entries

  resources :delivery_modes

  resources :providers

  resources :circles

  resources :groups

  resources :gift_categories

  resources :event_categories

  resources :locations

  resources :zwajusers

  post '/rate' => 'rater#create', :as => 'rate'
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'

  root 'welcome#index'

  

  

end

app/models/event_category.rb
class EventCategory < ActiveRecord::Base

  validates :name, :description, presence: true

  belongs_to  :parent,        class_name: "EventCategory"
  has_many    :subcategories, class_name: "EventCategory", foreign_key: "parent_id"
  has_many    :events
  has_many    :gifts
  has_many    :services

end

app/controllers/event_categories_controller.rb
class EventCategoriesController < ApplicationController
  before_action :set_event_category, only: [:show, :edit, :update, :destroy]

  # GET /event_categories
  # GET /event_categories.json
  def index
    @event_categories = EventCategory.all
  end

  # GET /event_categories/1
  # GET /event_categories/1.json
  def show
  end

  # GET /event_categories/new
  def new
    @event_category = EventCategory.new
  end

  # GET /event_categories/1/edit
  def edit
  end

  # POST /event_categories
  # POST /event_categories.json
  def create
    @event_category = EventCategory.new(event_category_params)

    respond_to do |format|
      if @event_category.save
        format.html { redirect_to @event_category, notice: 'Event category was successfully created.' }
        format.json { render action: 'show', status: :created, location: @event_category }
      else
        format.html { render action: 'new' }
        format.json { render json: @event_category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /event_categories/1
  # PATCH/PUT /event_categories/1.json
  def update
    respond_to do |format|
      if @event_category.update(event_category_params)
        format.html { redirect_to @event_category, notice: 'Event category was successfully updated.' }
        format.json { render action: 'show', status: :ok, location: @event_category }
      else
        format.html { render action: 'edit' }
        format.json { render json: @event_category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /event_categories/1
  # DELETE /event_categories/1.json
  def destroy
    @event_category.destroy
    respond_to do |format|
      format.html { redirect_to event_categories_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_event_category
      @event_category = EventCategory.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def event_category_params
      params[:event_category].permit(:name, :description)
    end
end

app/helpers/event_categories_helper.rb
module EventCategoriesHelper
end

app/views/event_categories/_form.html.erb
<%= form_for(@event_category) do |f| %>
  <% if @event_category.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@event_category.errors.count, "error") %> prohibited this event_category from being saved:</h2>

      <ul>
      <% @event_category.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/event_categories/edit.html.erb
<h1>Editing event_category</h1>

<%= render 'form' %>

<%= link_to 'Show', @event_category %> |
<%= link_to 'Back', event_categories_path %>

app/views/event_categories/index.html.erb
<h1>Listing event_categories</h1>

<table>
  <thead>
    <tr>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @event_categories.each do |event_category| %>
      <tr>
        <td><%= link_to 'Show', event_category %></td>
        <td><%= link_to 'Edit', edit_event_category_path(event_category) %></td>
        <td><%= link_to 'Destroy', event_category, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Event category', new_event_category_path %>

app/views/event_categories/new.html.erb
<h1>New event_category</h1>

<%= render 'form' %>

<%= link_to 'Back', event_categories_path %>

app/views/event_categories/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_event_category_path(@event_category) %> |
<%= link_to 'Back', event_categories_path %>