config/routes.rb
Zwaj::Application.routes.draw do
  
  resources :notifications

  resources :events

  resources :services

  resources :activities

  resources :themes

  resources :albums

  resources :gifts

  resources :entries

  resources :delivery_modes

  resources :providers

  resources :circles

  resources :groups

  resources :gift_categories

  resources :event_categories

  resources :locations

  resources :zwajusers

  post '/rate' => 'rater#create', :as => 'rate'
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'

  root 'welcome#index'

  

  

end

app/controllers/notifications_controller.rb
require 'reloader/sse'
class NotificationsController < ApplicationController
  before_action :set_notification, only: [:show, :edit, :update, :destroy]
  include ActionController::Live

  # GET /notifications
  # GET /notifications.json
  def index
    response.headers['Content-Type'] = 'text/event-stream'
    sse                              = Reloader::SSE.new(response.stream)
    channels                         = %i(public_activities )
    redis                            = Redis.new(url: ZWAJ_CONFIG['REDIS_URL'])  #, driver: :hiredis
    begin
      #stream redis subscribe
      redis.subscribe(*channels) do |on|
        on.subscribe do |channel, subscriptions|
          Rails.logger.debug "Subscribed to ##{channel} (#{subscriptions} subscriptions)"
        end

        on.message do |channel, message|
          sse.write(message, event: channel)
          Rails.logger.debug "##{channel}: #{message}"
          redis.unsubscribe if message == "exit"
        end

        on.unsubscribe do |channel, subscriptions|
          Rails.logger.debug "Unsubscribed from ##{channel} (#{subscriptions} subscriptions)"
        end
      end
    rescue Redis::BaseConnectionError => error
      Rails.logger.error "#{error}, retrying in 1s"
      sleep 1
      retry
    rescue IOError => error
      # When the client disconnects, we'll get an IOError on write
      Rails.logger.error "IOError:: #{error}"
    ensure
      sse.close
      redis.unsubscribe 
    end 
  end

  # GET /notifications/1
  # GET /notifications/1.json
  def show
  end

  # GET /notifications/new
  def new
    @notification = Notification.new
  end

  # GET /notifications/1/edit
  def edit
  end

  # POST /notifications
  # POST /notifications.json
  def create
    @notification = Notification.new(notification_params)

    respond_to do |format|
      if @notification.save
        format.html { redirect_to @notification, notice: 'Notification was successfully created.' }
        format.json { render action: 'show', status: :created, location: @notification }
      else
        format.html { render action: 'new' }
        format.json { render json: @notification.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /notifications/1
  # PATCH/PUT /notifications/1.json
  def update
    respond_to do |format|
      if @notification.update(notification_params)
        format.html { redirect_to @notification, notice: 'Notification was successfully updated.' }
        format.json { render action: 'show', status: :ok, location: @notification }
      else
        format.html { render action: 'edit' }
        format.json { render json: @notification.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /notifications/1
  # DELETE /notifications/1.json
  def destroy
    @notification.destroy
    respond_to do |format|
      format.html { redirect_to notifications_url }
      format.json { head :no_content }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_notification
    @notification = Notification.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def notification_params
    params[:notification]
  end
end

app/helpers/notifications_helper.rb
module NotificationsHelper
end

app/views/notifications/_form.html.erb
<%= form_for(@notification) do |f| %>
  <% if @notification.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@notification.errors.count, "error") %> prohibited this notification from being saved:</h2>

      <ul>
      <% @notification.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/notifications/edit.html.erb
<h1>Editing notification</h1>

<%= render 'form' %>

<%= link_to 'Show', @notification %> |
<%= link_to 'Back', notifications_path %>

app/views/notifications/index.html.erb
<h1>Listing notifications</h1>

<table>
  <thead>
    <tr>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @notifications.each do |notification| %>
      <tr>
        <td><%= link_to 'Show', notification %></td>
        <td><%= link_to 'Edit', edit_notification_path(notification) %></td>
        <td><%= link_to 'Destroy', notification, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Notification', new_notification_path %>

app/views/notifications/new.html.erb
<h1>New notification</h1>

<%= render 'form' %>

<%= link_to 'Back', notifications_path %>

app/views/notifications/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_notification_path(@notification) %> |
<%= link_to 'Back', notifications_path %>