config/routes.rb
Zwaj::Application.routes.draw do
  
  resources :notifications

  resources :events

  resources :services

  resources :activities

  resources :themes

  resources :albums

  resources :gifts

  resources :entries

  resources :delivery_modes

  resources :providers

  resources :circles

  resources :groups

  resources :gift_categories

  resources :event_categories

  resources :locations

  resources :zwajusers

  post '/rate' => 'rater#create', :as => 'rate'
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'

  root 'welcome#index'

  

  

end

app/models/activity.rb
class Activity < ActiveRecord::Base



 # include Concerns::Zwajletsrate
  zwaj_letsrate_rateable "feelings"

  store_accessor :action_params, :object_id, :object_type

  belongs_to :active, polymorphic: true
  belongs_to :user



  def self.possible_actions
    %w( event_creation comment rating new_picture new_video  )
  end

  validates :action, :active_id, :active_type, :user_id  , presence: true
  validates :action, inclusion: {in: possible_actions}

end

app/controllers/activities_controller.rb
require 'mailbox'

class ActivitiesController < ApplicationController
  before_action :set_activity, only: [:show, :edit, :update, :destroy]

  # GET /activities
  # GET /activities.json
  def index
    @activities = Activity.all
  end

  # GET /activities/1
  # GET /activities/1.json
  def show
  end

  # GET /activities/new
  def new
    @activity = Activity.new
  end

  # GET /activities/1/edit
  def edit
  end

  # POST /activities
  # POST /activities.json
  def create
    @activity = Activity.new(activity_params)

    respond_to do |format|
      if @activity.save
        #Send notifications to users interested in the activity
        format.html { redirect_to @activity, notice: 'Activity was successfully created.' }
        format.json { render action: 'show', status: :created, location: @activity }
      else
        format.html { render action: 'new' }
        format.json { render json: @activity.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /activities/1
  # PATCH/PUT /activities/1.json
  def update
    respond_to do |format|
      if @activity.update(activity_params)
        format.html { redirect_to @activity, notice: 'Activity was successfully updated.' }
        format.json { render action: 'show', status: :ok, location: @activity }
      else
        format.html { render action: 'edit' }
        format.json { render json: @activity.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /activities/1
  # DELETE /activities/1.json
  def destroy
    @activity.destroy
    respond_to do |format|
      format.html { redirect_to activities_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_activity
      @activity = Activity.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def activity_params
      params[:activity].permit(:action, :active_id, :active_type, :user_id )
    end

end

app/helpers/activities_helper.rb
module ActivitiesHelper
end

app/views/activities/_form.html.erb
<%= form_for(@activity) do |f| %>
  <% if @activity.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@activity.errors.count, "error") %> prohibited this activity from being saved:</h2>

      <ul>
      <% @activity.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/activities/edit.html.erb
<h1>Editing activity</h1>

<%= render 'form' %>

<%= link_to 'Show', @activity %> |
<%= link_to 'Back', activities_path %>

app/views/activities/index.html.erb
<h1>Listing activities</h1>

<table>
  <thead>
    <tr>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @activities.each do |activity| %>
      <tr>
        <td><%= link_to 'Show', activity %></td>
        <td><%= link_to 'Edit', edit_activity_path(activity) %></td>
        <td><%= link_to 'Destroy', activity, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Activity', new_activity_path %>

app/views/activities/new.html.erb
<h1>New activity</h1>

<%= render 'form' %>

<%= link_to 'Back', activities_path %>

app/views/activities/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_activity_path(@activity) %> |
<%= link_to 'Back', activities_path %>